#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.
#By Saksham Madan

#This is brute foece method, will work if you have high enough computational power.

n = 4000000
def  Fibonacci(nterms):
    # first two terms
    n1, n2 = 1, 2
    count = 0
    arr = []
    while count < nterms:
        arr.append(n1)
        nth = n1 + n2
        # update values
        n1 = n2
        n2 = nth
        count += 1
    
    return arr

arr = []

arr = Fibonacci(n)
sum = 0
for i in arr:
    if i%2 == 0:
        sum = sum + i

print(sum)
